### ISSUE TITLE
Nextcloud plugin doesn't work as expected on latest Nextcloud 13.0.4

### ISSUE THREAD

**Issue by ganesh-at-wiw** [GluuFederation/nextcloud-oxd-plugin#8]
Nextcloud plugin doesn't work as expected on latest Nextcloud 13.0.4. It was installed, but not usable. The configuration screen never appears.

**Comment by ganesh-at-wiw** [comment]
Nextcloud plugin was installed now but from log, we get this error:

`{"reqId":"pQ68o369fs34kgTbiUfF","level":3,"time":"2018-07-11T18:10:42+00:00","remoteAddr":"192.168.2.200","user":"--","app":"index","method":"GET","url":"\/nextcloud\/index.php\/apps\/gluusso\/loginpage?requesttoken=UCiYJ5yuEMf1eEsWHxQS4HyCHNxyyKqEDxtGCP%2BiPJc%3D%3AOhjUXtDhUZ6TNHN%2BfiIhsjapTqtGpt%2FoXW8gfJL1eu0%3D","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OC_Util::rememberLoginAllowed()\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\GluuSso\\\\Controller\\\\PageController->loginpage(NULL, NULL, NULL)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\GluuSso\\\\Controller\\\\PageController), 'loginpage')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\GluuSso\\\\Controller\\\\PageController), 'loginpage')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\GluuSso\\\\\\\\Con...', 'loginpage', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/gluusso\\\/l...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/index.php(42): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/gluusso\\\/lib\\\/Controller\\\/PageController.php\",\"Line\":1449}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/66.0.3359.181 Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.4.0"}
`
